### ISSUE TITLE
alternate plugin is broken due changes in forward plugin

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [coredns/alternate#11]
For now alternate plugin is broken due changes in forward plugin:
ParseForwardStanza() -> parseStanza(c)
Could we keep ParseForwardStanza()?
cc: @miekg @chrisohaver @johnbelamaric @rdrozhdzh @ rsvalerio

**Comment by chrisohaver** [comment]
> Could we keep ParseForwardStanza()?

I understand that this was intentionally removed because making plugins directly interdependent is not desirable.

See #4 for some possible solutions (packagifying parts of forward, or replicating code).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/alternate] alternate p..." ]
>> Could we keep ParseForwardStanza()?
>
>I understand that this was intentionally removed because making plugins directly interdependent is not desirable.
>
>See #4 for some possible solutions (packagifying parts of forward, or replicating code).

copy it

**Comment by UladzimirTrehubenka** [comment]
Resolved - see https://github.com/coredns/alternate/pull/14
