### ISSUE TITLE
Use a single alternate block to reduce repetition

### ISSUE THREAD

**Issue by andrewlouis93** [coredns/alternate#12]
In the use-case where you want to forward the query based on multiple rcodes; I currently have to do something like this:

```
alternate NXDOMAIN . 192.168.1.1:53
alternate SERVFAIL . 192.168.1.1:53
```

Would like to submit a pull-request to make a single block support multiple rcodes, but was looking for some insight into how the interface should look. As it is a non-optional argument, I _think_ it should be inlined like so: 

```
alternate NXDOMAIN,SERVFAIL . 192.168.1.1:53
```

Let me know what you folks think.

**Comment by chrisohaver** [comment]
Seems reasonable to me.

**Comment by andrewlouis93** [comment]
Thanks @chrisohaver! I'll put a PR together
