### ISSUE TITLE
Unable to use this plugin

### ISSUE THREAD

**Issue by OriolOMM** [coredns/alternate#20]
Hi,

I compiled the plugin with coredns.

My Corefile looks like this:

```
.:533 {
    forward . 8.8.8.8
    alternate NXDOMAIN . 127.0.0.1:5353
    log
}
```

Query to 127.0.0.1:533 for a domain that exist in 127.0.0.1:5353 returns NXDOMAIN. Also shutting down DNS server on 127.0.0.1:5353 and running the query again doesn't produce any error in coredns logs. Strange...

How I can see if `alternate` is running?

Regards.

**Comment by isavcic** [comment]
Same here. Compiled against v1.8.0 CoreDNS. Compilation goes okay, but:

```
. {
        forward . 104.199.179.254
        alternate REFUSED . 1.1.1.1
}
```
returns `REFUSED`, but when configuration is changed to forward to 1.1.1.1 (without `alternate`), the 1.1.1.1 resolver can of course resolve the record; tried with `google.com A`.

BTW, @OriolOMM you can see the plugin is "running" because CoreDNS doesn't complain there's the keyword `alternate`.

**Comment by isavcic** [comment]
I wonder, why didn't the tests catch this?

**Comment by chrisohaver** [comment]
In what order are _forward_ and _alternate_ plugins listed in your `plugin.cfg`?

**Comment by isavcic** [comment]
Same as in README.md: first `forward`, then `alternate`.

**Comment by chrisohaver** [comment]
> Same as in README.md: first `forward`, then `alternate`.

The readme shows several Corefile examples.... but the Corefile is different than the `/plugin.cfg` file that you are required to change in CoreDNS when compiling in external plugins, such as this one.  A very common mistake is to add external plugins to the end of the list, but `plugin.cfg` defines execution order of plugins.  The order of plugins the Corefile does not matter. If _forward_ is executed before alternate, _alternate_ never processes anything.

**Comment by isavcic** [comment]
@chrisohaver Wow, thanks! Sorry, I misread, I thought you meant Corefile... Indeed, when I put alternate on top of plugin.cfg and recompiled, it works!

**Comment by OriolOMM** [comment]
Changing the order of the plugin in plugin.cfg worked. Thanks
