### ISSUE TITLE
Support nested alternates

### ISSUE THREAD

**Issue by patricklundquist** [coredns/alternate#22]
I'm interested in adding an alternate for an alternate. For example, something like this:
...
alternate NXDOMAIN . 8.8.8.8 {
    alternate NXDOMAIN . 192.168.1.1:53
}

Is that possible? Let me know what you folks think.

**Comment by chrisohaver** [comment]
> I'm interested in adding an alternate for an alternate.

I think that can be interpreted in different ways.
You might be able to do what you want with local forwarding (i.e. forwarding to localhost on another port that coredns listens to).

**Comment by chrisohaver** [comment]
e.g. 

If the response from to 10.0.0.1 is NXDOMAIN, try 10.0.0.2, if that response is NXDOMAIN, try 10.0.0.3 ...


```
. {
  forward . 10.0.0.1
  alternate NXDOMAIN 127.0.0.1:5399
}

.:5399 {
  forward .  10.0.0.2
  alternate NXDOMAIN  10.0.0.3
}
```

**Comment by chrisohaver** [comment]
The external plugin _fanout_ (https://coredns.io/explugins/fanout/) might also be able to do what you want.  Setting worker count to 1, it checks a series of upstreams in order, and returns the first non-negative response.

**Comment by patricklundquist** [comment]
Thanks for the quick reply! Fanout looks like it will work for my use case.
